repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        files: ^rozert-pay/
      - id: end-of-file-fixer
        files: ^rozert-pay/
      - id: check-yaml
        files: ^rozert-pay/
      - id: check-json
        files: ^rozert-pay/

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^rozert-pay/

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
        files: ^rozert-pay/

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--ignore=E501,W503,F811"
          - "--exclude=rozert_pay/migrations"
        files: ^rozert-pay/
        additional_dependencies: [flake8-print]
